### ISSUE TITLE
Transition between traditional and simplified Chinese

### ISSUE THREAD

**Issue by cqx931** [dhowe/Automachar#15]
The trigger doesn't seem to be connected to the traditional/simplified Chinese changing process. 

As an example:
4)突襲 -> 突袭
this is a traditional to simplified Chinese transition, but there is no trigger identified in the logger.

Later there is a trigger:
trigger: "書" in "上書" -> simp

but the actual transition happened at
15) 正書 -> 正旦 2s 'starring female role in a Chinese opera' (right, proper, correct / dawn; morning; day)

<img width="298" alt="Screenshot 2020-07-06 at 11 21 18 AM" src="https://user-images.githubusercontent.com/3056154/86610068-d2192500-bf7a-11ea-800f-a6c3e9007da1.png">

**Comment by dhowe** [comment]
can this be closed?

**Comment by cqx931** [comment]
yes
