### ISSUE TITLE
Stuck large stroke

### ISSUE THREAD

**Issue by dhowe** [dhowe/Automachar#2]
>the anomalous thing that I am seeing is (confirmed by a number of viewings and on all platforms available to me) : the first stroke of the lefthand character is both too large and also out of place (too low and too far to the right), screen shot follows (the vertical stroke should be part of the lefthand character's 'mouth' radical

![2019-07-28 00 54 14](https://user-images.githubusercontent.com/737638/62002447-3d534980-b0d2-11e9-8e27-83327a46516d.jpg)

**Comment by cqx931** [comment]
I noticed that this issue only happens when the rendering area is smaller than the canvas size. Haven't figured out when and why the rendering area will become smaller yet, but this should be the right direction to go.

**Comment by cqx931** [comment]
This is fixed now. 
ctx.setTransform() used to be called after each stroke is rendered for a word, therefore the transformation could potentially be different for the first stroke for every word. 
It might be related to some default differences across different display settings. When the default setting was the same as the parameters we set in setTransform() this is not an issue; But if the default setting is different, we will see an error.
