### ISSUE TITLE
Critical bug in loading window

### ISSUE THREAD

**Issue by dhowe** [dhowe/Automachar#21]
When I run the sketch locally in Chrome, if I click before the loading animation is done, then the sketch starts by itself when the animation/loading has finished. This is the correct behavior.

However, when I try the same test on the live site (https://rednoise.org/rotvh/), a click before the loading animation has finished causes the screen to go blank and remain that way.

**Comment by cqx931** [comment]
Hmm, I just tried the link in my chrome but I can't reproduce the blank page.
