### ISSUE TITLE
Update info overlay

### ISSUE THREAD

**Issue by dhowe** [dhowe/Automachar#7]
info overlay (after you click the 3 vertical bars in upper-left hand corner)

- [x] is using absolute pixels, and thus doesn’t work correctly in mobile
- [x] should pop up on load, with a loading message (perhaps blinking). User must click to close the window and start the piece. If user clicks before loading has finished, nothing should happen
- [x] clicking should enable the sound (this will happen automatically I believe)

**Comment by dhowe** [comment]
this looks really good, though on some mobile I still see incorrect layout:

![Screenshot 2020-07-03 at 1 22 15 PM](https://user-images.githubusercontent.com/737638/86434603-6ba0c680-bd30-11ea-8029-f985166499b9.png)

**Comment by cqx931** [comment]
This should have fixed the rest of the mobile cases.
https://github.com/dhowe/autochar/pull/11

**Comment by cqx931** [comment]
can this one be closed?
